# Generated by Django 2.2.11 on 2020-04-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekplan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '未完了'), (2, '作業中'), (3, '完了')], default=1),
        ),
    ]
